apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: ci-story-api
  name: ci-story-api
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/Estafet-LTD/estafet-microservices-scrum-api-story"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ci-pipeline.groovy
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0